# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# 密码种子文件secrets.yml (ruby on rails用到的密码种子配置文件)

development:
  secret_key_base: 015ea18f4f9ce77579866dacfe853ab110af147e0efcaa5ad3d1758dc0606af141729bdddb5d01c2abb3ea3f0b5d27c38a77e7147e4db133923a9197c686f7b3

test:
  secret_key_base: 015ea18f4f9ce77579866dacfe853ab110af147e0efcaa5ad3d1758dc0606af141729bdddb5d01c2abb3ea3f0b5d27c38a77e7147e4db133923a9197c686f7b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 015ea18f4f9ce77579866dacfe853ab110af147e0efcaa5ad3d1758dc0606af141729bdddb5d01c2abb3ea3f0b5d27c38a77e7147e4db133923a9197c686f7b3
